title: webcoder.info
description: Internet information & resources
google_analytics: UA-61854432-1
show_downloads: false
theme: jekyll-theme-slate
markdown: GFM

plugins:
  - jemoji
  - jekyll-mermaid
  - jekyll-asciidoc
